# Generated by Django 6.0 on 2025-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
