# Generated by Django 4.2.7 on 2025-12-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventsubmission_rsvp_alter_event_options_and_more'),
    ]

    operations = [
    ]
