# Generated by Django 5.2.9 on 2025-12-30 02:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_merge_20251230_0045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='interested', max_length=20)),
                ('num_guests', models.PositiveIntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EventSubmission',
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='event',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_date_13e470_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_event_t_a87b5c_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_registration_open',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_details',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('exhibition', 'Exhibition'), ('run', 'Run'), ('talk', 'Talk'), ('field_visit', 'Field Visit'), ('seminar', 'Seminar'), ('conference', 'Conference')], default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'event_type'], name='events_even_date_5a7630_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_0ae1f4_idx'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event'),
        ),
        migrations.DeleteModel(
            name='RSVP',
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'email')},
        ),
    ]
