# Generated by Django 6.0 on 2025-12-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qualification',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2),
        ),
    ]
